### ISSUE TITLE
Archivo can't find Tivo from Win 10 PC unless Tivo Desktop is installed

### ISSUE THREAD

**Issue by scottfeier** [fflewddur/archivo#53]
I'm running a Win 10 PC, current version of Java, Norton Internet Security (and hence their firewall, not the native Windows firewall), Tivo Roamio OTA.

I installed Archivo, and it was unable to find the Tivo (spinning circle in lower left of UI saying Searching for Tivo).  I already had Bonjour installed thanks to iTunes, so that wasn't the issue.

On a hunch, I installed Tivo Desktop.  Tivo Desktop found my Tivo, and after that installation, so did Archivo.

Not sure if it was that the Tivo desktop install changed some firewall rules, or something else, but it would be nice to run Archivo without needing the Tivo Desktop installed.

Am happy to experiment with any suggestions you may have.

**Comment by fflewddur** [comment]
Thanks for reporting this Scott. I'm guessing one of two things is happening here:

1) Maybe Norton was blocking Archivo from accessing the network port it needs to search for TiVos, but I'm not sure why installing TiVo Desktop would suddenly fix that.

2) I've received reports from a few folks that Archivo can't find their TiVos while certain other software is running, including older versions of Plex and certain releases of nVidia's Experience software. What seems to be happening is these programs are locking the port Archivo needs to search for TiVos, and as soon as they shut down the offending program, Archivo is able to find their TiVos. I'm guessing that may be happening here as well, because there's no link between TiVo Desktop and Archivo. To test this, you should be able to completely uninstall TiVo Desktop, then start up Archivo. If it suddenly can't find your TiVo again, then the idea that something in the TiVo Desktop installation opened up a hole in Norton's firewall seems much more likely, so the next troubleshooting step would be to disable the firewall and startup Archivo. If that works, then we know it's a firewall issue and I can look into ensure Archivo is whitelisted by Norton going forward.

**Comment by scottfeier** [comment]
Thanks Todd—I’m traveling this week, I’ll experiment when I’m back home next week.

**Comment by scottfeier** [comment]
Took,me a while to do some testing.  If I run the Plex server first, Archivo can't find the Tivo.  If I don't run Plex first, it works fine.  If I start Plex first, then I have to reboot to get Archivo to work.  I'm using the most current version of Plex.

**Comment by fflewddur** [comment]
Hey Scott, thanks for digging into this! I'm testing with what I think is the latest version of Plex (also on Win10), but I'm not seeing the same error. Just to confirm, my Plex server says its version 0.9.16.4.1911; does yours say the same?

I also checked out Plex's port usage with Resource Monitor, but I don't see it using the same socket as Archivo. I've attached a screenshot; if you open up Resource Monitor, go to the Network tab, expand the Network Activity section, and then sort by address. Check to see what else is listening to address 224.0.0.251. I'm curious if your Plex server is configured differently than mine, and somehow blocking the socket for that address. Or maybe some other service is blocking it; either way, it should show up in that list. Bonjour and svchost will also likely show up there, but neither seems to block the socket (at least on my machine).

![resource monitor](https://cloud.githubusercontent.com/assets/5544445/14590470/216e20e0-04b0-11e6-8351-d64c8ab4e603.PNG)

**Comment by scottfeier** [comment]
Looks like Bonjour has the same address.  This time, it happened after an hour of random PC use that did not include starting Plex.  So I think that, for me, starting Plex first is guaranteed to hose Archivo, but other activities may do so as well
![network capture](https://cloud.githubusercontent.com/assets/1932307/14623780/20c0c992-05a3-11e6-8a96-23a094f27238.PNG)

**Comment by fflewddur** [comment]
Thanks for your help gathering more info about this, Scott! I think I finally have a fix. Could you try downloading the attached hola-0.1.3.jar.zip file, unzip it, and replace the hola-0.1.3.jar file in C:\Program Files (x86)\Archivo with it? Let me know if it helps.
[hola-0.1.3.jar.zip](https://github.com/fflewddur/archivo/files/229221/hola-0.1.3.jar.zip)

**Comment by scottfeier** [comment]
Okay, I gave it a try. No go--that is, the library works, but it doesn't seem to change the issue.  I did learn a bit more, though--the problem seems to be one of time and some unknown background process, more than an action on my part.  If I start Archivo within the first minute or so after login, it works, but if I start it after that, it will fail, _even if I started it earlier_ .  So there must be some startup process on my machine that takes a while to load--if I start Archivo before it loads, it will work but once it loads, it won't.

Suggestions?  I could go through the logs in the Event Viewer if I knew what to look for.

**Comment by fflewddur** [comment]
Hey Scott, I just released an update that might resolve this; it's available at https://github.com/fflewddur/archivo/releases/tag/v1.0.2. Can you let me know if this helps?

**Comment by scottfeier** [comment]
Tried 1.0.3, so far it seems to have no problems starting and finding my Tivo.  Thanks for your efforts, if I see a repeat of the issue I'll let you know.

**Comment by fflewddur** [comment]
Awesome, thanks Scott!
